//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Student
    {
        public int Id { get; set; }

        [DisplayName("Student Name")]
        [Required(ErrorMessage ="Name is Required")]
        public string Name { get; set; }

        [DisplayName("Student Email")]
        [Required(ErrorMessage = "Email is Required")]
        public string Email { get; set; }

        [DisplayName("Student Gender")]
        [Required(ErrorMessage = "Gender is Required")]
        public string Gender { get; set; }

        [DisplayName("Student Age")]
        [Required(ErrorMessage = "Age is Required")]
        public int Age { get; set; }

        [DisplayName("Student Address")]
        [Required(ErrorMessage = "Address is Required")]
        public string Address { get; set; }
    }
}
